---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: latest

inputs:
- name: code
- name: tasks

run:
  path: tasks/tasks/html_proofer.sh

params:
  DOMAIN:
