---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: alpine

inputs:
- name: code
- name: concourse

run:
  path: concourse/tasks/html_proofer.sh

params:
  DOMAIN:
