---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 18fgsa/html-proofer

inputs:
- name: code
- name: concourse

run:
  path: concourse/tasks/html_proofer.sh

params:
  DOMAIN:
  FILE_IGNORES:
