---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 'latest'

inputs:
- name: code
- name: tasks

outputs:
- name: site

run:
  path: tasks/tasks/jekyll.sh
