---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3.1'

inputs:
- name: code
- name: tasks

params:
  AWS_Access:
  AWS_Secret:
  AWS_Bucket:
  AWS_Zone:

run:
  path: tasks/tasks/jekyll_deploy_s3.sh

