---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hrektts/mdbook
    tag: 'latest'

inputs:
- name: code
- name: tasks

outputs:
- name: book

run:
  path: tasks/tasks/mdbook.sh
