---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hrektts/mdbook
    tag: latest

inputs:
- name: code
- name: concourse

outputs:
- name: book

run:
  path: concourse/tasks/mdbook.sh
