---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: tmaier/markdown-spellcheck

inputs:
- name: code

run:
  path: mdspell
  args:
  - --ignore-acronyms
  - --ignore-numbers
  - --en-us
  - --report
  - "src/**/*.md"
  user: node
  dir: code
