---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ibmcom/swift-ubuntu
    tag: 'latest'

inputs:
- name: code
- name: concourse

run:
  path: concourse/tasks/swiftpm_tests.sh
