---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: swiftdocker/swift
    tag: latest

inputs:
- name: code
- name: concourse

run:
  path: concourse/tasks/fastlane_tests.sh
